# Generated by Django 4.1.7 on 2023-04-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('codigo_cliente', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('codigo_material', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('nombre_material', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo_producto', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('codigo_proveedor', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=300)),
            ],
        ),
    ]
