# Generated by Django 4.1.7 on 2023-04-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=200)),
                ('especie', models.CharField(max_length=200)),
                ('cantidad_kg', models.CharField(blank=True, max_length=200)),
                ('cantidad_caja', models.CharField(blank=True, max_length=200)),
                ('precio_kg', models.CharField(blank=True, max_length=200)),
                ('precio_caja', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
