# Generated by Django 4.1.7 on 2023-04-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_entradas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entradas',
            new_name='Entrada',
        ),
    ]
