# Generated by Django 4.1.7 on 2023-04-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_entrada_especie_alter_entrada_nombre_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='entrada',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.materiales'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='nombre_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.proveedores'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.productos'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='nombre_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.clientes'),
        ),
    ]
