# Generated by Django 4.1.7 on 2023-04-27 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_productos_options_alter_entrada_especie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='entrada',
            options={'verbose_name_plural': 'Entradas'},
        ),
        migrations.AlterModelOptions(
            name='materiales',
            options={'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='salida',
            options={'verbose_name_plural': 'Salidas'},
        ),
        migrations.AddField(
            model_name='entrada',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salida',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
