# Generated by Django 4.1.7 on 2023-05-05 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_entrada_codigo_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='codigo_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.proveedores'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='nombre_proveedor',
            field=models.CharField(max_length=300),
        ),
    ]
