# Generated by Django 4.1.7 on 2023-05-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_entrada_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='codigo_especie',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='codigo_proveedor',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
