# Generated by Django 4.1.7 on 2023-05-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_entrada_codigo_especie_alter_entrada_especie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='lote',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
