# Generated by Django 4.1.7 on 2023-05-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_entrada_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='lote',
            field=models.CharField(default='', max_length=50),
        ),
    ]
