# Generated by Django 4.1.7 on 2023-05-10 15:43

from django.db import migrations, models
def set_default_lote(apps, schema_editor):
    Entrada = apps.get_model('app', 'Entrada')
    Entrada.objects.filter(lote=None).update(lote='')

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_entrada_lote'),
    ]

    operations = [
        migrations.RunPython(set_default_lote),
    ]
