# Generated by Django 4.1.7 on 2023-05-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_entrada_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='lote',
            field=models.CharField(blank=True, default='1', max_length=50, null=True),
        ),
    ]
