# Generated by Django 4.1.7 on 2023-05-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_entrada_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='albaran',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='codigo_arte_pesca',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='codigo_barco',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='codigo_zona_captura',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='fecha_captura',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
