# Generated by Django 4.1.7 on 2023-05-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_entrada_albaran_entrada_codigo_arte_pesca_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='nombre_proveedor',
            new_name='nombre_proveedor_id',
        ),
    ]
