# Generated by Django 4.1.7 on 2023-05-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_nombre_proveedor_entrada_nombre_proveedor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='nombre_proveedor_id',
            new_name='nombre_proveedor',
        ),
    ]
