# Generated by Django 4.1.7 on 2023-05-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_nombre_proveedor_id_entrada_nombre_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
