# Generated by Django 4.1.7 on 2023-05-22 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_entrada_fecha_captura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='codigo_arte_pesca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.artespesca'),
        ),
    ]
