# Generated by Django 4.1.7 on 2023-05-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_entrada_codigo_arte_pesca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='codigo_arte_pesca',
            new_name='codigo_arte',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='codigo_zona_captura',
        ),
        migrations.AddField(
            model_name='entrada',
            name='codigo_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.zonasfao'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='codigo_barco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.barcos'),
        ),
    ]
