# Generated by Django 4.1.7 on 2023-05-22 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_codigo_arte_pesca_entrada_codigo_arte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='codigo_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.clientes'),
        ),
        migrations.AddField(
            model_name='salida',
            name='codigo_especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.productos'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_captura',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='salida',
            name='especie',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='salida',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
