# Generated by Django 4.1.7 on 2023-05-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_salida_codigo_cliente_salida_codigo_especie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salida',
            old_name='codigo_cliente',
            new_name='codigo_cliente_id',
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='codigo_especie',
            new_name='codigo_especie_id',
        ),
    ]
